name: Deploy to Render

on:
  workflow_run:
    workflows: ["Spring Boot CI with H2"]  # 這是 CI 工作流程的名稱
    types:
      - completed  # 當 CI 完成時觸發此工作流程

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Deploy to Render (Trigger deploy via Render API)
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST https://api.render.com/v1/services/YOUR_SERVICE_ID/deploy \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -d "{}"