services:
  db:
    image: mysql:8.0.22
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: springboot
      MYSQL_DATABASE: mall
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mall
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: springboot