version: '3.8'

services:
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: springboot
      MYSQL_DATABASE: mall
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - ./.env:/app/.env
    working_dir: /app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mall
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: springboot