name: Spring Boot CI with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Show Docker Compose version
        run: docker-compose --version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: docker-compose version

      - name: Build and start with Docker Compose
        run: docker-compose -f ./docker-compose.yml up --build -d

      - name: Wait until MySQL is healthy
        run: |
          echo "Waiting for healthy services..."
          timeout 60s bash -c 'until docker-compose -f ./docker-compose.yml ps | grep "healthy"; do sleep 2; done'

      - name: Run Integration Tests
        run: docker-compose -f ./docker-compose.yml exec -T app mvn test

      - name: Shutdown
        if: always()
        run: docker-compose -f ./docker-compose.yml down
