name: Spring Boot CI with H2 and Redis

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Wait for Redis to be ready
        run: |
          for i in {1..10}; do
            redis-cli -h localhost ping && break
            echo "Waiting for Redis..."
            sleep 2
          done

      - name: Build and run tests
        run: cd springboot-mall && mvn clean verify

