name: Spring Boot CI with Docker Compose

on:
  push:
    branches:
      - main  # 當 push 到 main 分支時觸發此工作流程

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install OpenJDK 17
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          java -version

      - name: Build with Maven (compile and test)
        run: |
          cd springboot-mall  # 切換到包含 pom.xml 的目錄
          mvn clean install  # 執行編譯與測試

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build Docker Image
        run: |
          docker build -t your_docker_image_name .  # 建立 Docker 鏡像

      - name: Push Docker Image to Docker Hub (or another registry)
        run: |
          docker push your_docker_image_name  # 將鏡像推送到 Docker Hub 或其他倉庫
